const data = {
  station: [
    { name: "Chennai" },
    { name: "Vellore" },
    { name: "Bangalore" },
    { name: "Mysuru" },
    { name: "Mangalore" },
    { name: "Shimoga" },
  ],
  train: [
    {
      name: "TrainA",
      source: "Chennai",
      destination: "Vellore",
      departureTime: "09:00",
      arrivalTime: "11:00",
      distance: 170,
    },
    {
      name: "TrainA",
      source: "Chennai",
      destination: "Bangalore",
      departureTime: "09:00",
      arrivalTime: "15:30",
      distance: 370,
    },
    {
      name: "TrainA",
      source: "Chennai",
      destination: "Mysuru",
      departureTime: "09:00",
      arrivalTime: "17:30",
      distance: 490,
    },
    {
      name: "TrainA",
      source: "Chennai",
      destination: "Mangalore",
      departureTime: "09:00",
      arrivalTime: "21:45",
      distance: 790,
    },
    {
      name: "TrainA",
      source: "Vellore",
      destination: "Bangalore",
      departureTime: "11:00",
      arrivalTime: "15:30",
      distance: 200,
    },
    {
      name: "TrainA",
      source: "Vellore",
      destination: "Mysuru",
      departureTime: "11:00",
      arrivalTime: "17:30",
      distance: 320,
    },
    {
      name: "TrainA",
      source: "Vellore",
      destination: "Mangalore",
      departureTime: "11:00",
      arrivalTime: "21:45",
      distance: 620,
    },
    {
      name: "TrainA",
      source: "Bangalore",
      destination: "Mysuru",
      departureTime: "15:30",
      arrivalTime: "17:30",
      distance: 120,
    },
    {
      name: "TrainA",
      source: "Bangalore",
      destination: "Mangalore",
      departureTime: "21:45",
      arrivalTime: "17:30",
      distance: 420,
    },
    {
      name: "TrainA",
      source: "Mysuru",
      destination: "Mangalore",
      departureTime: "17:30",
      arrivalTime: "21:45",
      distance: 300,
    },
    {
      name: "TrainB",
      source: "Bangalore",
      destination: "Shimoga",
      departureTime: "09:00",
      arrivalTime: "12:00",
      distance: 180,
    },
    {
      name: "TrainB",
      source: "Bangalore",
      destination: "Mangalore",
      departureTime: "09:00",
      arrivalTime: "17:30",
      distance: 430,
    },
    {
      name: "TrainB",
      source: "Shimoga",
      destination: "Mangalore",
      departureTime: "12:00",
      arrivalTime: "17:30",
      distance: 250,
    },
    {
      name: "TrainC",
      source: "Bangalore",
      destination: "Shimoga",
      departureTime: "16:00",
      arrivalTime: "19:00",
      distance: 180,
    },
    {
      name: "TrainC",
      source: "Bangalore",
      destination: "Mangalore",
      departureTime: "16:00",
      arrivalTime: "23:45",
      distance: 430,
    },
    {
      name: "TrainC",
      source: "Shimoga",
      destination: "Mangalore",
      departureTime: "19:00",
      arrivalTime: "23:45",
      distance: 250,
    },
  ],
};
module.exports = data;
